# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_postview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
